version: 2
sources:
  - name: STAGE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: PC_MATILLION_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS