version: 2
sources:
  - name: RAW
    description: This is as source for STAGE
    database: PC_MATILLION_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS
  - name: STAGE
    description: This is a source for Publish
    database: PC_MATILLION_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS